### ISSUE TITLE
setup will fail

### ISSUE THREAD

**Issue by bawsuser** [xanonDev/pinkcord#52]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dvtw5ojt/pypiwin32_d5087b4131714bc882a38e04c47fabba/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/elo/Desktop/pinkcord/src/Setup.py", line 380, in <module>
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', 'requirements.txt'])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-r', 'requirements.txt']' returned non-zero exit status 1.

on linux mint 
python Python 3.10.12

**Comment by Jvr2022** [comment]
Did the virtual machine worked?

**Comment by bawsuser** [comment]
the virtual machine worked well thanks

**Comment by Jvr2022** [comment]
Ok then this can be closed
